connect:
  facebook:
    key: "d4da5246592e79b7148f09e9367070a4"
    secret: "e812e0a5876c5812440648578b98aff7"
    label: "Facebook"
    options:
      scope: ""
  linked_in:
    key: "3qcWfnMhLdFiHCHLhA9YuAudUL5_Di-IBkb-5A75J8VqjSzOk7J-Nz1nEhOhu6ge"
    secret: "_fzN_wIEVqoMyWmnprovAFc5QJqEoD543JOby2tQ2Ftuk3CgYZegV8q5r5cNhwht"
    label: "LinkedIn"